version: '2'
services: 
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  weblogger1:
    image: fpommerening/msrmq:logging-web
    depends_on:
      - rabbitmq
    hostname: weblogger1
    environment:
      - ConnectingStringRabbitMQ=host=rabbitmq
    
  weblogger2:
    image: fpommerening/msrmq:logging-web
    depends_on:
      - rabbitmq
    hostname: weblogger2
    environment:
      - ConnectingStringRabbitMQ=host=rabbitmq

  weblogger3:
    image: fpommerening/msrmq:logging-web
    depends_on:
      - rabbitmq
    hostname: weblogger3
    environment:
      - ConnectingStringRabbitMQ=host=rabbitmq

  loadbalancer:
    image: fpommerening/msrmq:logging-loadbalancer
    depends_on:
      - weblogger1
      - weblogger2
      - weblogger3
    ports:
      - 80
    hostname: loadbalancer
      
# logconsole:
#   image: fpommerening/msrmq:logging-console
#   depends_on: 
#     - RabbitMQ
#   hostname: logconsole

  loggingcaller:
    image: fpommerening/msrmq:logging-caller
    depends_on: 
      - loadbalancer
    hostname: loggingcaller
    environment:
      - TargetUrl=http://loadbalancer:80/Service/
